name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run change detection
      run: node test-scripts/change-detection.js
    
    - name: Execute tests
      run: npm test
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/